import { useMemo, useState } from 'react';
import { Timestamp } from 'firebase/firestore';
import { differenceInDays } from 'date-fns';
import { motion } from 'framer-motion';
import {
  AlertCircle,
  Bell,
  Calendar,
  CheckCircle2,
  Clock3,
  Pencil,
  Plus,
  Search,
  Sparkles,
  Trash2,
} from 'lucide-react';
import { useDataStore } from '@/store/dataStore';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { formatDate, formatRelativeTime, getCategoryColor, cn, parseDateInputValue } from '@/lib/utils';
import { showToast } from '@/lib/notifications';
import type { PriorityLevel, Reminder, ReminderCategory, ReminderStatus } from '@/types';
import { getSectionTheme } from '@/lib/sectionTheme';

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.4,
      ease: [0.16, 1, 0.3, 1] as const,
    },
  },
};

const statusBadgeClassNames: Record<ReminderStatus, string> = {
  pending: 'border-amber-500/20 bg-amber-500/10 text-amber-600 dark:text-amber-300',
  completed: 'border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-300',
  snoozed: 'border-sky-500/20 bg-sky-500/10 text-sky-600 dark:text-sky-300',
};

const priorityBadgeClassNames: Record<Reminder['priority'], string> = {
  low: 'border-slate-500/20 bg-slate-500/10 text-slate-600 dark:text-slate-300',
  medium: 'border-sky-500/20 bg-sky-500/10 text-sky-600 dark:text-sky-300',
  high: 'border-orange-500/20 bg-orange-500/10 text-orange-600 dark:text-orange-300',
};

export const RemindersPage = () => {
  const {
    reminders,
    completeReminder,
    deleteReminder,
    updateReminder,
  } = useDataStore();
  const [searchQuery, setSearchQuery] = useState('');
  const [activeTab, setActiveTab] = useState<ReminderStatus | 'all'>('all');
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);

  const filteredReminders = useMemo(
    () =>
      reminders
        .filter((item) => {
          const matchesSearch =
            item.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
            item.description?.toLowerCase().includes(searchQuery.toLowerCase());
          const matchesStatus = activeTab === 'all' || item.status === activeTab;
          return matchesSearch && matchesStatus;
        })
        .sort((left, right) => left.dueDate.toDate().getTime() - right.dueDate.toDate().getTime()),
    [activeTab, reminders, searchQuery],
  );

  const stats = useMemo(() => {
    const pending = reminders.filter((item) => item.status === 'pending');
    const completed = reminders.filter((item) => item.status === 'completed').length;
    const snoozed = reminders.filter((item) => item.status === 'snoozed').length;
    const dueToday = pending.filter(
      (item) => differenceInDays(item.dueDate.toDate(), new Date()) === 0,
    ).length;
    const overdue = pending.filter(
      (item) => differenceInDays(item.dueDate.toDate(), new Date()) < 0,
    ).length;
    const highPriority = pending.filter((item) => item.priority === 'high').length;
    const autoGenerated = reminders.filter((item) => item.autoGenerated).length;
    const nextReminder = [...pending].sort(
      (left, right) => left.dueDate.toDate().getTime() - right.dueDate.toDate().getTime(),
    )[0];

    return {
      pending: pending.length,
      completed,
      snoozed,
      dueToday,
      overdue,
      highPriority,
      autoGenerated,
      nextReminder,
    };
  }, [reminders]);

  const reminderFlowRows = [
    {
      label: 'Pending reminders',
      value: stats.pending,
      display: stats.pending.toString(),
      helper: 'Open follow-ups',
      color: '#38bdf8',
      max: Math.max(reminders.length, 1),
    },
    {
      label: 'Completed',
      value: stats.completed,
      display: stats.completed.toString(),
      helper: 'Handled items',
      color: '#14b8a6',
      max: Math.max(reminders.length, 1),
    },
    {
      label: 'Needs attention',
      value: stats.overdue + stats.dueToday,
      display: (stats.overdue + stats.dueToday).toString(),
      helper: stats.overdue > 0 ? `${stats.overdue} overdue` : `${stats.dueToday} due today`,
      color: '#f59e0b',
      max: Math.max(stats.pending, 1),
    },
    {
      label: 'Auto reminders',
      value: stats.autoGenerated,
      display: stats.autoGenerated.toString(),
      helper: 'Generated from records',
      color: '#8b5cf6',
      max: Math.max(reminders.length, 1),
    },
  ];

  const handleDeleteReminder = async (reminder: Reminder) => {
    const shouldDelete = confirm(
      reminder.autoGenerated
        ? `Delete the automatic reminder series for "${reminder.title}"?`
        : `Delete "${reminder.title}"?`,
    );

    if (!shouldDelete) return;

    await deleteReminder(reminder.id);
    showToast({
      title: reminder.autoGenerated ? 'Automatic reminder series removed' : 'Reminder deleted',
      type: 'success',
    });
  };

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="arcora-feature-page arcora-orbit-dashboard space-y-5"
    >
      <motion.div
        variants={itemVariants}
        className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"
      >
        <div>
          <p className="text-2xl font-semibold tracking-tight text-slate-950 dark:text-slate-50">
            Reminders
          </p>
          <p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500 dark:text-slate-400">
            Manual follow-ups, automatic nudges, and deadline context in the same clean workspace as your dashboard.
          </p>
        </div>

        <div className="flex flex-wrap gap-2">
          <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
            <DialogTrigger asChild>
              <Button className="rounded-full bg-blue-600 px-4 text-white hover:bg-blue-500">
                <Plus className="mr-2 h-4 w-4" />
                Add Reminder
              </Button>
            </DialogTrigger>

            <DialogContent className="max-h-[85vh] max-w-lg overflow-y-auto rounded-[1.5rem] border-border/70 bg-card/95 p-0 shadow-[0_28px_90px_rgba(15,23,42,0.22)] backdrop-blur-2xl dark:bg-slate-950/95">
              <DialogHeader>
                <DialogTitle className="px-6 pt-6">Add Reminder</DialogTitle>
              </DialogHeader>
              <AddReminderForm onSuccess={() => setIsAddDialogOpen(false)} />
            </DialogContent>
          </Dialog>
        </div>
      </motion.div>

      <motion.div variants={itemVariants} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <ReminderMetricCard
          icon={Bell}
          label="Pending"
          value={stats.pending.toString()}
          helper={`${stats.dueToday} due today`}
          colors={['#2563eb', '#0e7490']}
          values={[0, stats.pending, stats.dueToday, stats.pending + 1, stats.overdue]}
        />
        <ReminderMetricCard
          icon={CheckCircle2}
          label="Completed"
          value={stats.completed.toString()}
          helper={`${stats.snoozed} snoozed`}
          colors={['#0f766e', '#115e59']}
          values={[0, stats.completed, stats.snoozed, stats.completed + 1, stats.completed]}
        />
        <ReminderMetricCard
          icon={AlertCircle}
          label="Needs Attention"
          value={(stats.overdue + stats.dueToday).toString()}
          helper={stats.overdue > 0 ? `${stats.overdue} overdue` : 'All clear'}
          colors={['#b45309', '#92400e']}
          values={[stats.overdue, stats.dueToday, stats.highPriority, stats.pending, stats.overdue]}
        />
        <ReminderMetricCard
          icon={Sparkles}
          label="Auto Nudges"
          value={stats.autoGenerated.toString()}
          helper="From records"
          colors={['#7c3aed', '#5b21b6']}
          values={[0, stats.autoGenerated, stats.autoGenerated + 1, stats.pending, stats.autoGenerated]}
        />
      </motion.div>

      <motion.div variants={itemVariants} className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]">
        <Card className="border-sky-100 bg-white p-0 dark:border-white/10 dark:bg-white/[0.07]">
          <CardContent className="p-5">
            <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <p className="text-base font-semibold text-slate-950 dark:text-slate-50">Reminder Flow</p>
                <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                  Follow-ups, completion pace, and generated deadline nudges that need attention.
                </p>
              </div>
              <Badge className="rounded-full border-0 bg-sky-500/12 text-sky-700 hover:bg-sky-500/12 dark:text-sky-200">
                {stats.pending} open
              </Badge>
            </div>

            <div className="mt-6 grid gap-4 lg:grid-cols-[minmax(0,1fr)_240px]">
              <div className="space-y-4">
                {reminderFlowRows.map((row) => (
                  <div key={row.label}>
                    <div className="flex items-center justify-between gap-3 text-sm">
                      <div>
                        <p className="font-semibold text-slate-700 dark:text-slate-200">{row.label}</p>
                        <p className="mt-0.5 text-[11px] text-slate-400">{row.helper}</p>
                      </div>
                      <span className="text-xs font-semibold text-slate-500 dark:text-slate-300">{row.display}</span>
                    </div>
                    <div className="mt-2 h-3 rounded-full bg-slate-100 dark:bg-white/10">
                      <div
                        className="h-full rounded-full"
                        style={{ width: `${Math.min(100, (row.value / row.max) * 100)}%`, backgroundColor: row.color }}
                      />
                    </div>
                  </div>
                ))}
              </div>

              <div className="rounded-2xl bg-[linear-gradient(135deg,#2563eb,#0e7490)] p-4 text-white">
                <div className="grid h-11 w-11 place-items-center rounded-full border border-white/25 bg-white/15">
                  <Bell className="h-5 w-5" />
                </div>
                <p className="mt-5 text-sm font-semibold">Deadline Rhythm</p>
                <p className="mt-1 text-xs leading-5 text-white/75">
                  Keep due dates, manual tasks, and automatic record reminders visible before they become stressful.
                </p>
                <div className="mt-5 grid grid-cols-2 gap-2 text-center text-xs">
                  <span className="rounded-xl bg-white/15 px-3 py-2">{stats.highPriority} priority</span>
                  <span className="rounded-xl bg-white/15 px-3 py-2">{stats.autoGenerated} auto</span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-sky-100 bg-white p-0 dark:border-white/10 dark:bg-white/[0.07]">
          <CardContent className="p-5">
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="text-xs font-semibold uppercase tracking-[0.25em] text-sky-700/80 dark:text-sky-300/80">
                  Next Reminder
                </p>
                <p className="mt-2 text-xl font-semibold text-slate-950 dark:text-slate-50">
                  {stats.nextReminder ? stats.nextReminder.title : 'Everything is on track'}
                </p>
              </div>
              <div className="rounded-2xl border border-sky-500/15 bg-sky-500/10 p-3">
                <Clock3 className="h-5 w-5 text-sky-600 dark:text-sky-300" />
              </div>
            </div>

            <p className="mt-4 text-sm leading-6 text-slate-500 dark:text-slate-400">
              {stats.nextReminder
                ? `Due ${formatRelativeTime(stats.nextReminder.dueDate).toLowerCase()}. Keeping it visible here helps the rest of your week stay calmer.`
                : 'No pending reminders are waiting for attention right now.'}
            </p>

            <div className="mt-5 space-y-3 rounded-[1.35rem] border border-slate-200 bg-slate-50/80 p-4 dark:border-white/10 dark:bg-white/5">
              <SummaryRow
                label="Due"
                value={stats.nextReminder ? formatDate(stats.nextReminder.dueDate) : 'All clear'}
              />
              <SummaryRow
                label="Priority"
                value={stats.nextReminder ? stats.nextReminder.priority : 'Calm'}
              />
              <SummaryRow
                label="Status"
                value={stats.nextReminder ? stats.nextReminder.status : 'On track'}
              />
            </div>

            <div className="mt-5 grid grid-cols-2 gap-3">
              <ReminderCompactMetric label="Due Today" value={stats.dueToday.toString()} />
              <ReminderCompactMetric label="Overdue" value={stats.overdue.toString()} />
              <ReminderCompactMetric label="Completed" value={stats.completed.toString()} />
              <ReminderCompactMetric label="Auto" value={stats.autoGenerated.toString()} />
            </div>
          </CardContent>
        </Card>
      </motion.div>

      <motion.div variants={itemVariants} className="flex flex-col gap-4 md:flex-row">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search reminders or notes..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="h-12 rounded-2xl border-border/70 pl-10"
          />
        </div>

        <select
          value={activeTab}
          onChange={(e) => setActiveTab(e.target.value as ReminderStatus | 'all')}
          className="h-12 rounded-2xl border border-border/70 bg-background px-4 text-sm"
        >
          <option value="all">All Reminders</option>
          <option value="pending">Pending</option>
          <option value="completed">Completed</option>
          <option value="snoozed">Snoozed</option>
        </select>
      </motion.div>

      <motion.div variants={itemVariants}>
        {filteredReminders.length === 0 ? (
          <Card className="border-dashed border-orange-500/20 bg-orange-500/5">
            <CardContent className="py-14 text-center">
              <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-[1.4rem] border border-orange-500/20 bg-orange-500/10">
                <Bell className="h-7 w-7 text-orange-600 dark:text-orange-300" />
              </div>
              {reminders.length === 0 ? (
                <>
                  <h3 className="mt-5 text-xl font-semibold">Add your first reminder before something slips</h3>
                  <p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-muted-foreground">
                    Start with one deadline or task and Arcora will help keep important follow-ups visible before they turn into stress.
                  </p>
                  <Button variant="outline" onClick={() => setIsAddDialogOpen(true)} className="mt-5 rounded-full">
                    <Plus className="mr-2 h-4 w-4" />
                    Add Reminder
                  </Button>
                </>
              ) : (
                <>
                  <h3 className="mt-5 text-xl font-semibold">No reminders match this view</h3>
                  <p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-muted-foreground">
                    Try another filter, or add another reminder to keep tasks and deadlines easier to stay ahead of.
                  </p>
                </>
              )}
            </CardContent>
          </Card>
        ) : (
          <div className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3">
            {filteredReminders.map((reminder) => (
              <ReminderCard
                key={reminder.id}
                reminder={reminder}
                onComplete={completeReminder}
                onEdit={updateReminder}
                onDelete={handleDeleteReminder}
              />
            ))}
          </div>
        )}
      </motion.div>
    </motion.div>
  );
};

const ReminderCard = ({
  reminder,
  onComplete,
  onEdit,
  onDelete,
}: {
  reminder: Reminder;
  onComplete: (id: string) => Promise<void>;
  onEdit: (id: string, data: Partial<Reminder>) => Promise<void>;
  onDelete: (reminder: Reminder) => Promise<void>;
}) => {
  const remindersTheme = getSectionTheme('reminders');
  const isAutoReminder = reminder.autoGenerated && Boolean(reminder.targetDate);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);

  return (
    <motion.div
      variants={itemVariants}
      whileHover={{ y: -6, transition: { duration: 0.2, ease: 'easeOut' } }}
      whileTap={{ scale: 0.985 }}
      className="h-full"
    >
      <Card className="h-full border-border/70 bg-card/80">
        <CardContent className="flex h-full flex-col p-5">
          <div className="flex items-start justify-between gap-3">
            <div className="space-y-2">
              <div className="flex flex-wrap items-center gap-2">
                <Badge className={cn('capitalize border-transparent', getCategoryColor(reminder.category))}>
                  {reminder.category}
                </Badge>
                <Badge variant="outline" className={cn('capitalize', statusBadgeClassNames[reminder.status])}>
                  {reminder.status}
                </Badge>
                <Badge variant="outline" className={cn('capitalize', priorityBadgeClassNames[reminder.priority])}>
                  {reminder.priority}
                </Badge>
                {reminder.autoGenerated ? (
                  <Badge variant="outline" className="border-border/60 text-muted-foreground">
                    Auto
                  </Badge>
                ) : null}
              </div>
              <div>
                <h3 className="line-clamp-2 text-lg font-semibold">{reminder.title}</h3>
                <p className="text-sm text-muted-foreground">
                  {isAutoReminder
                    ? `Reminder ${formatRelativeTime(reminder.dueDate).toLowerCase()}`
                    : formatRelativeTime(reminder.dueDate)}
                </p>
              </div>
            </div>

            <div className={cn('rounded-2xl p-3', remindersTheme.iconWrapClassName)}>
              <Calendar className={cn('h-5 w-5', remindersTheme.iconClassName)} />
            </div>
          </div>

          <div className="mt-5 rounded-[1.3rem] border border-border/60 bg-muted/25 p-4">
            <p className="line-clamp-3 text-sm leading-6 text-muted-foreground">
              {reminder.description || 'No additional notes for this reminder yet.'}
            </p>
          </div>

          <div
            className={cn(
              'mt-5 gap-3 text-sm text-muted-foreground',
              isAutoReminder ? 'grid grid-cols-2 md:grid-cols-3' : 'grid grid-cols-2',
            )}
          >
            <div>
              <p className="text-[11px] uppercase tracking-[0.24em] text-muted-foreground/80">
                {isAutoReminder ? 'Reminder Date' : 'Due Date'}
              </p>
              <p className="mt-1">{formatDate(reminder.dueDate)}</p>
            </div>
            {isAutoReminder ? (
              <div>
                <p className="text-[11px] uppercase tracking-[0.24em] text-muted-foreground/80">
                  Target Date
                </p>
                <p className="mt-1">{formatDate(reminder.targetDate!)}</p>
              </div>
            ) : null}
            <div>
              <p className="text-[11px] uppercase tracking-[0.24em] text-muted-foreground/80">
                Source
              </p>
              <p className="mt-1">{reminder.autoGenerated ? 'Automatic' : 'Manual'}</p>
            </div>
          </div>

          <div className="mt-auto grid grid-cols-1 gap-2 pt-5 sm:grid-cols-3">
            <Button
              variant="outline"
              disabled={reminder.status === 'completed'}
              onClick={() => onComplete(reminder.id)}
              className="rounded-full"
            >
              <CheckCircle2 className="mr-2 h-4 w-4" />
              {reminder.status === 'completed' ? 'Done' : 'Complete'}
            </Button>
            <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
              <DialogTrigger asChild>
                <Button variant="outline" className="rounded-full">
                  <Pencil className="mr-2 h-4 w-4" />
                  Edit
                </Button>
              </DialogTrigger>
              <DialogContent className="max-h-[85vh] max-w-lg overflow-y-auto rounded-[1.5rem] border-border/70 bg-card/95 p-0 shadow-[0_28px_90px_rgba(15,23,42,0.22)] backdrop-blur-2xl dark:bg-slate-950/95">
                <DialogHeader>
                  <DialogTitle className="px-6 pt-6">Edit Reminder</DialogTitle>
                </DialogHeader>
                <AddReminderForm
                  reminder={reminder}
                  onSubmit={async (data) => {
                    await onEdit(reminder.id, data);
                    setIsEditDialogOpen(false);
                  }}
                />
              </DialogContent>
            </Dialog>
            <Button
              variant="ghost"
              onClick={() => onDelete(reminder)}
              className="rounded-full text-muted-foreground hover:text-destructive"
            >
              <Trash2 className="mr-2 h-4 w-4" />
              Delete
            </Button>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
};

const AddReminderForm = ({
  onSuccess,
  reminder,
  onSubmit,
}: {
  onSuccess?: () => void;
  reminder?: Reminder;
  onSubmit?: (data: Partial<Reminder>) => Promise<void>;
}) => {
  const { addReminder } = useDataStore();
  const isEditing = Boolean(reminder);

  const [title, setTitle] = useState(reminder?.title ?? '');
  const [description, setDescription] = useState(reminder?.description ?? '');
  const [dueDate, setDueDate] = useState(
    reminder ? toDateInputValue(reminder.dueDate.toDate()) : '',
  );
  const [category, setCategory] = useState<ReminderCategory>(reminder?.category ?? 'personal');
  const [priority, setPriority] = useState<PriorityLevel>(reminder?.priority ?? 'medium');
  const [saving, setSaving] = useState(false);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!title || !dueDate) return;

    const parsedDueDate = parseDateInputValue(dueDate);
    if (!parsedDueDate) return;

    setSaving(true);
    try {
      const payload: Partial<Reminder> = {
        title,
        description: isEditing ? description : description || undefined,
        dueDate: Timestamp.fromDate(parsedDueDate),
        category,
        priority,
      };

      if (isEditing && onSubmit) {
        await onSubmit(payload);
      } else {
        await addReminder({
          title,
          description: description || undefined,
          dueDate: Timestamp.fromDate(parsedDueDate),
          priority,
          category,
          status: 'pending',
          isRecurring: false,
          reminderSent: {
            thirtyDays: false,
            sevenDays: false,
            oneDay: false,
            onDueDate: false,
          },
        });
      }

      showToast({
        title: isEditing ? 'Reminder updated' : 'Reminder added',
        type: 'success',
      });

      onSuccess?.();
    } finally {
      setSaving(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4 px-6 pb-6 pt-2">
      <div className="space-y-2">
        <label className="text-sm font-medium">Title</label>
        <Input
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="Pay electricity bill"
          required
          className="h-12 rounded-2xl border-border/70 bg-background/70"
        />
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium">Description</label>
        <textarea
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          rows={4}
          className="w-full rounded-2xl border border-border/70 bg-background/70 px-4 py-3 text-sm outline-none transition-colors focus:border-primary/50 focus:ring-2 focus:ring-primary/15"
          placeholder="Optional details"
        />
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium">Due Date</label>
        <Input
          type="date"
          value={dueDate}
          onChange={(e) => setDueDate(e.target.value)}
          required
          className="h-12 rounded-2xl border-border/70 bg-background/70"
        />
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium">Category</label>
        <select
          value={category}
          onChange={(e) => setCategory(e.target.value as ReminderCategory)}
          className="h-12 w-full rounded-2xl border border-border/70 bg-background/70 px-4 text-sm outline-none transition-colors focus:border-primary/50 focus:ring-2 focus:ring-primary/15"
        >
          <option value="personal">Personal</option>
          <option value="finance">Finance</option>
          <option value="work">Work</option>
          <option value="health">Health</option>
          <option value="other">Other</option>
        </select>
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium">Priority</label>
        <select
          value={priority}
          onChange={(e) => setPriority(e.target.value as PriorityLevel)}
          className="h-12 w-full rounded-2xl border border-border/70 bg-background/70 px-4 text-sm outline-none transition-colors focus:border-primary/50 focus:ring-2 focus:ring-primary/15"
        >
          <option value="low">Low</option>
          <option value="medium">Medium</option>
          <option value="high">High</option>
        </select>
      </div>

      <Button type="submit" className="h-11 w-full rounded-full" disabled={saving}>
        {saving ? 'Saving...' : isEditing ? 'Save Changes' : 'Add Reminder'}
      </Button>
    </form>
  );
};

const toDateInputValue = (date: Date) => {
  const year = date.getFullYear();
  const month = `${date.getMonth() + 1}`.padStart(2, '0');
  const day = `${date.getDate()}`.padStart(2, '0');
  return `${year}-${month}-${day}`;
};

const ReminderMetricCard = ({
  icon: Icon,
  label,
  value,
  helper,
  colors,
  values,
}: {
  icon: React.ElementType;
  label: string;
  value: string;
  helper: string;
  colors: [string, string];
  values: number[];
}) => {
  const wave = getReminderSparkline(values, 220, 50);

  return (
    <div
      className="relative min-h-36 overflow-hidden rounded-[1.15rem] p-5 text-white shadow-[0_14px_32px_rgba(15,23,42,0.16)]"
      style={{ background: `linear-gradient(135deg, ${colors[0]}, ${colors[1]})` }}
    >
      <div className="relative z-10 flex items-start justify-between gap-3">
        <div className="grid h-11 w-11 place-items-center rounded-2xl bg-white/[0.18]">
          <Icon className="h-5 w-5" />
        </div>
        <span className="rounded-full bg-white/[0.18] px-2.5 py-1 text-[10px] font-bold">
          {helper}
        </span>
      </div>
      <p className="relative z-10 mt-5 text-2xl font-semibold leading-none">{value}</p>
      <p className="relative z-10 mt-2 text-xs font-medium text-white/80">{label}</p>
      <svg viewBox="0 0 220 62" className="absolute inset-x-0 bottom-0 h-16 w-full opacity-55">
        <path d={`M 0,62 L ${wave} L 220,62 Z`} fill="rgba(255,255,255,0.22)" />
        <polyline points={wave} fill="none" stroke="rgba(255,255,255,0.54)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    </div>
  );
};

const ReminderCompactMetric = ({ label, value }: { label: string; value: string }) => (
  <div className="rounded-2xl border border-sky-500/10 bg-sky-500/5 px-4 py-3">
    <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-slate-400">{label}</p>
    <p className="mt-2 text-lg font-semibold text-slate-950 dark:text-slate-50">{value}</p>
  </div>
);

const SummaryRow = ({ label, value }: { label: string; value: string }) => (
  <div className="flex items-center justify-between gap-3 text-sm">
    <span className="text-muted-foreground">{label}</span>
    <span className="font-medium capitalize text-foreground">{value}</span>
  </div>
);

const getReminderSparkline = (values: number[], width: number, height: number) => {
  const normalized = values.length > 0 ? values : [0];
  const max = Math.max(...normalized, 1);
  const min = Math.min(...normalized, 0);
  const range = Math.max(max - min, 1);
  const step = width / Math.max(normalized.length - 1, 1);

  return normalized
    .map((value, index) => {
      const x = index * step;
      const y = height - ((value - min) / range) * (height - 8) + 4;
      return `${x.toFixed(1)},${y.toFixed(1)}`;
    })
    .join(' ');
};
