import { format } from 'date-fns';
import type { QueryDocumentSnapshot } from 'firebase-admin/firestore';
import { admin, adminDb, adminMessaging } from '../firebase';

type ReminderSentKey = 'thirtyDays' | 'sevenDays' | 'oneDay' | 'onDueDate';

interface StoredReminderSentStatus {
  thirtyDays?: boolean;
  sevenDays?: boolean;
  oneDay?: boolean;
  onDueDate?: boolean;
}

interface StoredReminder {
  title?: string;
  description?: string;
  dueDate?: admin.firestore.Timestamp;
  targetDate?: admin.firestore.Timestamp;
  sourceDocumentId?: string;
  status?: 'pending' | 'completed' | 'snoozed';
  category?: string;
  relatedItemType?: string;
  relatedItemId?: string;
  autoGenerated?: boolean;
  autoGeneratedKind?: string;
  pushSentAt?: admin.firestore.Timestamp;
  reminderSent?: StoredReminderSentStatus;
}

interface StoredNotificationSettings {
  push?: boolean;
  billReminders?: boolean;
  warrantyAlerts?: boolean;
}

interface StoredUserSettings {
  notifications?: StoredNotificationSettings;
}

interface StoredNotificationDevice {
  token?: string;
  notificationsEnabled?: boolean;
}

interface PushJobSummary {
  scanned: number;
  eligible: number;
  delivered: number;
  skippedNoDevices: number;
  skippedDisabled: number;
  removedTokens: number;
  users: number;
}

const USER_BATCH_SIZE = 200;
const REMINDER_QUERY_BATCH_SIZE = 200;

const getReminderGroupKey = (reminderId: string, reminder: StoredReminder) => {
  if (!reminder.autoGenerated) {
    return reminderId;
  }

  if (reminder.sourceDocumentId) {
    return `document:${reminder.sourceDocumentId}`;
  }

  if (reminder.relatedItemType && reminder.relatedItemId) {
    return `${reminder.relatedItemType}:${reminder.relatedItemId}`;
  }

  return reminderId;
};

const selectReminderCandidates = (
  reminderDocs: QueryDocumentSnapshot<admin.firestore.DocumentData>[],
  now: Date,
) => {
  const grouped = new Map<string, QueryDocumentSnapshot<admin.firestore.DocumentData>[]>();

  reminderDocs.forEach((reminderDoc) => {
    const reminder = reminderDoc.data() as StoredReminder;
    const groupKey = getReminderGroupKey(reminderDoc.id, reminder);
    const group = grouped.get(groupKey) ?? [];
    group.push(reminderDoc);
    grouped.set(groupKey, group);
  });

  return [...grouped.values()].flatMap((group) => {
    const sorted = [...group].sort((left, right) => {
      const leftReminder = left.data() as StoredReminder;
      const rightReminder = right.data() as StoredReminder;

      return (leftReminder.dueDate?.toMillis() ?? 0) - (rightReminder.dueDate?.toMillis() ?? 0);
    });
    const future = sorted.filter((reminderDoc) => {
      const reminder = reminderDoc.data() as StoredReminder;
      return (reminder.dueDate?.toDate().getTime() ?? 0) >= now.getTime();
    });

    return [future[0] ?? sorted[sorted.length - 1]].filter(Boolean);
  });
};

const getPublicBaseUrl = () => {
  return process.env.PUSH_LINK_BASE_URL || process.env.PUBLIC_WEB_URL || '';
};

const buildReminderLink = () => {
  const baseUrl = getPublicBaseUrl().replace(/\/$/, '');
  return baseUrl ? `${baseUrl}/reminders` : '/reminders';
};

const getReminderSentKey = (reminder: StoredReminder): ReminderSentKey => {
  switch (reminder.autoGeneratedKind) {
    case '30_day_before':
      return 'thirtyDays';
    case '7_day_before':
    case '3_day_before':
      return 'sevenDays';
    case '1_day_before':
      return 'oneDay';
    case 'day_of':
    case 'overdue':
    case '1_day_after':
    default:
      return 'onDueDate';
  }
};

const isReminderTypeAllowed = (
  settings: StoredUserSettings | undefined,
  reminder: StoredReminder,
) => {
  const notifications = settings?.notifications;

  if (!notifications?.push) {
    return false;
  }

  if (reminder.relatedItemType === 'bill' || reminder.relatedItemType === 'subscription') {
    return notifications.billReminders !== false;
  }

  if (reminder.relatedItemType === 'warranty' || reminder.relatedItemType === 'document') {
    return notifications.warrantyAlerts !== false;
  }

  return true;
};

const buildNotificationCopy = (reminder: StoredReminder) => {
  const title = reminder.title?.trim() || 'Arcora reminder';

  if (reminder.description?.trim()) {
    return {
      title,
      body: reminder.description.trim(),
    };
  }

  if (reminder.targetDate) {
    return {
      title,
      body: `Target date: ${format(reminder.targetDate.toDate(), 'MMM d, yyyy')}. Open Arcora to review it.`,
    };
  }

  if (reminder.dueDate) {
    return {
      title,
      body: `Reminder date: ${format(reminder.dueDate.toDate(), 'MMM d, yyyy')}. Open Arcora to review it.`,
    };
  }

  return {
    title,
    body: 'Open Arcora to review what needs attention.',
  };
};

const removeInvalidTokens = async (
  deviceDocs: QueryDocumentSnapshot<admin.firestore.DocumentData>[],
  responses: Awaited<ReturnType<typeof adminMessaging.sendEachForMulticast>>['responses'],
) => {
  const invalidRefs = deviceDocs.flatMap((deviceDoc, index) => {
    const code = responses[index]?.error?.code;
    const invalid =
      code === 'messaging/invalid-registration-token' ||
      code === 'messaging/registration-token-not-registered';

    return invalid ? [deviceDoc.ref] : [];
  });

  if (invalidRefs.length === 0) {
    return 0;
  }

  const batch = adminDb.batch();
  invalidRefs.forEach((ref) => batch.delete(ref));
  await batch.commit();

  return invalidRefs.length;
};

const loadDueReminderDocs = async (
  userId: string,
  rangeEnd: admin.firestore.Timestamp,
) => {
  const reminderDocs: QueryDocumentSnapshot<admin.firestore.DocumentData>[] = [];
  let lastReminderDoc: QueryDocumentSnapshot<admin.firestore.DocumentData> | null = null;

  while (true) {
    let reminderQuery = adminDb
      .collection(`users/${userId}/reminders`)
      .where('dueDate', '<=', rangeEnd)
      .orderBy('dueDate', 'asc')
      .limit(REMINDER_QUERY_BATCH_SIZE);

    if (lastReminderDoc) {
      reminderQuery = reminderQuery.startAfter(lastReminderDoc);
    }

    const remindersSnapshot = await reminderQuery.get();
    if (remindersSnapshot.empty) {
      break;
    }

    reminderDocs.push(...remindersSnapshot.docs);

    if (remindersSnapshot.size < REMINDER_QUERY_BATCH_SIZE) {
      break;
    }

    lastReminderDoc = remindersSnapshot.docs[remindersSnapshot.docs.length - 1];
  }

  return reminderDocs;
};

export const sendPushReminders = async (): Promise<PushJobSummary> => {
  const now = new Date();
  const summary: PushJobSummary = {
    scanned: 0,
    eligible: 0,
    delivered: 0,
    skippedNoDevices: 0,
    skippedDisabled: 0,
    removedTokens: 0,
    users: 0,
  };

  const rangeEnd = admin.firestore.Timestamp.fromDate(now);
  let lastUserDoc: QueryDocumentSnapshot<admin.firestore.DocumentData> | null = null;

  while (true) {
    let usersQuery = adminDb
      .collection('users')
      .orderBy(admin.firestore.FieldPath.documentId())
      .limit(USER_BATCH_SIZE);

    if (lastUserDoc) {
      usersQuery = usersQuery.startAfter(lastUserDoc);
    }

    const usersSnapshot = await usersQuery.get();
    if (usersSnapshot.empty) {
      break;
    }

    summary.users += usersSnapshot.size;

    for (const userSnap of usersSnapshot.docs) {
      const userId = userSnap.id;
      const [devicesSnap, reminderDocsForUser] = await Promise.all([
        adminDb
          .collection(`users/${userId}/notificationDevices`)
          .where('notificationsEnabled', '==', true)
          .get(),
        loadDueReminderDocs(userId, rangeEnd),
      ]);

      const settings = userSnap.data()?.settings as StoredUserSettings | undefined;
      const reminderDocs = reminderDocsForUser.filter((reminderDoc) => {
        const reminder = reminderDoc.data() as StoredReminder;
        return reminder.status === 'pending' && !reminder.pushSentAt;
      });
      const selectedReminderDocs = selectReminderCandidates(reminderDocs, now);
      summary.scanned += reminderDocsForUser.length;

      if (devicesSnap.empty) {
        summary.skippedNoDevices += selectedReminderDocs.length;
        continue;
      }

      const activeDeviceDocs = devicesSnap.docs.filter((deviceDoc) => {
        const device = deviceDoc.data() as StoredNotificationDevice;
        return Boolean(device.token && device.notificationsEnabled);
      });

      if (activeDeviceDocs.length === 0) {
        summary.skippedNoDevices += selectedReminderDocs.length;
        continue;
      }

      for (const reminderDoc of selectedReminderDocs) {
        const reminder = reminderDoc.data() as StoredReminder;

        if (!isReminderTypeAllowed(settings, reminder)) {
          summary.skippedDisabled += 1;
          continue;
        }

        const validTokens = activeDeviceDocs
          .map((deviceDoc) => ({
            doc: deviceDoc,
            token: (deviceDoc.data() as StoredNotificationDevice).token,
          }))
          .filter((device) => Boolean(device.token));

        if (validTokens.length === 0) {
          summary.skippedNoDevices += 1;
          continue;
        }

        const sentKey = getReminderSentKey(reminder);
        const { title, body } = buildNotificationCopy(reminder);
        const notificationId = `push_${reminderDoc.id}_${reminder.dueDate?.seconds ?? Date.now()}`;
        const link = buildReminderLink();

        summary.eligible += 1;

        const sendResult = await adminMessaging.sendEachForMulticast({
          tokens: validTokens.map((device) => device.token as string),
          notification: {
            title,
            body,
          },
          data: {
            title,
            body,
            link,
            notificationId,
            reminderId: reminderDoc.id,
            relatedItemType: reminder.relatedItemType ?? 'reminder',
            relatedItemId: reminder.relatedItemId ?? reminderDoc.id,
          },
          webpush: {
            fcmOptions: link.startsWith('http')
              ? {
                  link,
                }
              : undefined,
            notification: {
              icon: '/icons/icon-192x192.png',
              badge: '/icons/icon-192x192.png',
              tag: notificationId,
            },
          },
        });

        summary.removedTokens += await removeInvalidTokens(
          validTokens.map((device) => device.doc),
          sendResult.responses,
        );

        if (sendResult.successCount === 0) {
          continue;
        }

        summary.delivered += sendResult.successCount;

        const reminderSent = reminder.reminderSent ?? {};

        await Promise.all([
          reminderDoc.ref.set(
            {
              reminderSent: {
                ...reminderSent,
                [sentKey]: true,
              },
              pushSentAt: admin.firestore.FieldValue.serverTimestamp(),
              updatedAt: admin.firestore.FieldValue.serverTimestamp(),
            },
            { merge: true },
          ),
          adminDb.doc(`users/${userId}/notifications/${notificationId}`).set({
            type: 'reminder',
            title,
            message: body,
            relatedItemType: reminder.relatedItemType ?? 'reminder',
            relatedItemId: reminder.relatedItemId ?? reminderDoc.id,
            read: false,
            createdAt: admin.firestore.FieldValue.serverTimestamp(),
          }),
        ]);
      }
    }

    if (usersSnapshot.size < USER_BATCH_SIZE) {
      break;
    }

    lastUserDoc = usersSnapshot.docs[usersSnapshot.docs.length - 1];
  }

  return summary;
};
