import type { Bill, Subscription, Warranty, Document, Reminder } from '@/types';

export type UrgencyItemType = 'bill' | 'subscription' | 'warranty' | 'document' | 'reminder';

export interface UrgencyItem {
  id: string;
  type: UrgencyItemType;
  title: string;
  date: Date;
  amount?: number;
  daysDiff: number; // 0 = today, positive = future, negative = past
  rawData: unknown;
}

export interface UrgencyBuckets {
  dueThisWeek: UrgencyItem[];
  expiringSoon: UrgencyItem[];
  overdue: UrgencyItem[];
}

/**
 * Calculates absolute day differences comparing only dates (ignoring time).
 */
function getDaysDiff(targetDate: Date): number {
  const now = new Date();
  const todayAtMidnight = Date.UTC(now.getFullYear(), now.getMonth(), now.getDate());
  const targetAtMidnight = Date.UTC(targetDate.getFullYear(), targetDate.getMonth(), targetDate.getDate());
  
  return Math.round((targetAtMidnight - todayAtMidnight) / (1000 * 60 * 60 * 24));
}

export function getUrgencyBuckets(
  bills: Bill[],
  subscriptions: Subscription[],
  warranties: Warranty[],
  documents: Document[],
  reminders: Reminder[]
): UrgencyBuckets {
  const dueThisWeek: UrgencyItem[] = [];
  const expiringSoon: UrgencyItem[] = [];
  const overdue: UrgencyItem[] = [];

  const addItem = (
    type: UrgencyItemType,
    id: string,
    title: string,
    date: Date,
    amount: number | undefined,
    rawData: unknown,
    isMajorId: boolean = false
  ) => {
    const daysDiff = getDaysDiff(date);
    const item: UrgencyItem = { id, type, title, date, amount, daysDiff, rawData };

    if (daysDiff < 0) {
      overdue.push(item);
    } else {
      // Future or today
      if (['bill', 'subscription', 'reminder'].includes(type) && daysDiff <= 7) {
        dueThisWeek.push(item);
      } else if (['warranty', 'document'].includes(type)) {
        const threshold = isMajorId ? 90 : 30; // 90 days for Passports/Licenses, 30 for warranties/generic docs
        if (daysDiff <= threshold) {
          expiringSoon.push(item);
        }
      }
    }
  };

  // Process Bills (only unpaid)
  bills.forEach(bill => {
    if (bill.status !== 'paid') {
      addItem('bill', bill.id, bill.title, bill.dueDate.toDate(), bill.amount, bill);
    }
  });

  // Process Subscriptions
  subscriptions.forEach(sub => {
    addItem('subscription', sub.id, sub.name, sub.nextRenewalDate.toDate(), sub.amount, sub);
  });

  // Process Warranties
  warranties.forEach(war => {
    addItem('warranty', war.id, war.productName, war.expirationDate.toDate(), undefined, war);
  });

  // Process Documents
  documents.forEach(doc => {
    if (doc.section !== 'documents' && doc.section !== 'others') {
      return;
    }

    const isMajor = doc.type === 'passport' || doc.type === 'license';
    
    const deadline = doc.expirationDate?.toDate();
    
    if (deadline) {
      // If it has a strict expiration date, use it.
      addItem('document', doc.id, doc.title, deadline, undefined, doc, isMajor);
    } else {
      // Check detected dates as fallback if needed, but let's stick to safe typed dates first.
      const detectedTarget = doc.detectedDates?.find(d => 
         ['due_date', 'expiry_date', 'renewal_date', 'deadline'].includes(d.type)
      );
      if (detectedTarget && detectedTarget.date) {
        const dateLike = detectedTarget.date as { toDate?: () => Date; seconds?: number };
        const dateObj = dateLike.toDate
            ? dateLike.toDate()
            : new Date((dateLike.seconds ?? 0) * 1000);
        addItem('document', doc.id, doc.title, dateObj, undefined, doc, isMajor);
      }
    }
  });

  // Process Reminders (only pending)
  reminders.forEach(rem => {
    if (rem.status === 'pending' && !rem.autoGenerated) {
        addItem('reminder', rem.id, rem.title, rem.dueDate.toDate(), undefined, rem);
    }
  });

  // Sort all buckets chronologically
  const sortByDate = (a: UrgencyItem, b: UrgencyItem) => a.date.getTime() - b.date.getTime();
  
  return {
    dueThisWeek: dueThisWeek.sort(sortByDate),
    expiringSoon: expiringSoon.sort(sortByDate),
    overdue: overdue.sort(sortByDate) // Most overdue (oldest) first
  };
}
